Repository NGCP/GCS, pull requests merged in 2020-02, with the labels that each got.

#76 Update package dependencies and pass tests
  .eslintrc.yml
  LICENSE
  package.json
  src/common/struct/Vehicle.ts
  src/main/index.ts
  src/renderer/mainWindow/log/LogContainer.tsx
  src/renderer/mainWindow/map/MapContainer.tsx
  src/renderer/missionWindow/extra/ActiveVehicleMapping.tsx
  src/renderer/missionWindow/extra/CreateBoundingBoxButton.tsx
  src/renderer/missionWindow/extra/CreateWaypointButton.tsx
  src/renderer/missionWindow/extra/MissionOptions.tsx
  src/util/util.ts
  typings/image.d.ts
  typings/leaflet.offline.d.ts
Labels: enhancement

#78 Simplify eslint with airbnb-typescript module
  .eslintignore
  .eslintrc.yml
  .stylelintignore
  .stylelintrc.yml
  .travis.yml
  package.json
  src/renderer/missionWindow/parameter/ISRSearch.tsx
  src/renderer/missionWindow/parameter/PayloadDrop.tsx
  src/renderer/missionWindow/parameter/UGVRescue.tsx
  src/renderer/missionWindow/parameter/VTOLSearch.tsx
  src/types/missionInformation.ts
Labels: enhancement

#80 Set TravisCI badge to track master branch
  README.rst
Labels: enhancement

#79 Add rules to make GCS repo support LF better
  .eslintrc.yml
  .gitattributes
  docs/contributing/getting-started.rst
  docs/contributing/rules.rst
  package.json
Labels: documentation, enhancement

#85 Merge docs script into one npm script
  package.json
Labels: documentation

#94 Add geofencing message structure
  src/common/struct/Vehicle.ts
  src/types/message.ts
Labels: enhancement

#96 Migrate docs to Markdown and update docs
  .eslintignore
  .gitignore
  .remarkrc.yml
  .stylelintignore
  README.md
  README.rst
  docs/communications/examples.rst
  docs/communications/examples/isr-search.rst
  docs/communications/implementation.rst
  docs/communications/introduction.md
  docs/communications/introduction.rst
  docs/communications/jobs-tasks/jobs-vs-tasks.md
  docs/communications/jobs-tasks/jobs.md
  docs/communications/jobs-tasks/tasks.md
  docs/communications/jobs.rst
  docs/communications/messages.rst
  docs/communications/messages/base-message.md
  docs/communications/messages/gcs-vehicles-messages.md
  docs/communications/messages/gcs-vehicles-messages.rst
  docs/communications/messages/implementation.md
  docs/communications/messages/other-messages.md
  docs/communications/messages/other-messages.rst
  docs/communications/messages/vehicles-gcs-messages.md
  docs/communications/messages/vehicles-gcs-messages.rst
  docs/communications/vehicle-ids.md
  docs/communications/vehicles.rst
  docs/conf.py
  docs/contributing/getting-started.md
  docs/contributing/getting-started.rst
  docs/contributing/guidelines.md
  docs/contributing/ncu.rst
  docs/contributing/rules.rst
  docs/img/icon.png
  docs/index.md
  docs/index.rst
  mkdocs.yml
  package.json
Labels: documentation
