Repository NGCP/GCS, pull requests merged in 2020-03, with the labels that each got.

#103 Add coverage through istanbul + coveralls
  .gitignore
  .travis.yml
  README.md
  package.json
Labels: enhancement

#102 Adding Geofence to Mission UI
  src/renderer/missionWindow/MissionWindow.tsx
  src/renderer/missionWindow/mission.css
Labels: enhancement

#106 Allow GCS to use latest version of electron
  package.json
  src/main/index.ts
Labels: enhancement

#109 Add script to test build in Travis
  .travis.yml
  package.json
Labels: enhancement

#111 Add GeofenceMessage to gcs-vehicles-messages.md
  docs/communications/messages/gcs-vehicles-messages.md
Labels: documentation, enhancement

#112 Add docs for including ts/tsx files in eslint atom
  docs/communications/messages/gcs-vehicles-messages.md
  docs/contributing/getting-started.md
  package.json
Labels: documentation

#116 Fix acknowledgement note on connectionAck messages
  docs/communications/messages/gcs-vehicles-messages.md
Labels: documentation
